#
# ██████╗░██╗░░░██╗  ███████╗███╗░░██╗░█████╗░░█████╗░░██████╗░
# ██╔══██╗╚██╗░██╔╝  ██╔════╝████╗░██║██╔══██╗██╔══██╗██╔════╝░
# ██████╦╝░╚████╔╝░  █████╗░░██╔██╗██║██║░░╚═╝██║░░██║██║░░██╗░
# ██╔══██╗░░╚██╔╝░░  ██╔══╝░░██║╚████║██║░░██╗██║░░██║██║░░╚██╗
# ██████╦╝░░░██║░░░  ███████╗██║░╚███║╚█████╔╝╚█████╔╝╚██████╔╝
# ╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚══╝░╚════╝░░╚════╝░░╚═════╝░
#
# Коды
codes:
  test:
    rewards:
      - 'give <player> minecraft:diamond 11'
    checkNick: true
    checkIP: true
    maxUsesPerAccount: 2
    maxUsesPerIP: 2
    message: '&fВы успешно использовали код!\n&fНаграды выданы!'
    title: '&aУспешно!'
    subtitle: '&fВы использовали код!'
  encog:
    rewards:
      - 'give <player> minecraft:obsidian 5'
      - 'give <player> minecraft:stone 2'
    checkNick: true
    checkIP: false
    maxUsesPerAccount: 1
    maxUsesPerIP: 1
    message: '&6➥ &fВы успешно использовали код от ENcoG!\n&fНаграды выданы!'
    title: '&aУспешно!'
    subtitle: '&fВы использовали код!'
# Сообщения
messages:
  alreadyUsed: "§fВы уже использовали этот код!"
  codeNotExist: "§fТакого кода не существует!"
  enterCode: "§fПожалуйста, введите код!"
  playersOnly: "§fТолько игроки могут использовать эту команду!"
